apiVersion: v2
name: kibana-stack
description: Wrapper chart for Kibana (via ECK)
type: application
version: 0.1.0
appVersion: "8.14.0"

dependencies:
  - name: kibana
    version: 8.14.0
    repository: https://helm.elastic.co
