apiVersion: v2
name: kibana-stack
description: Wrapper chart for Kibana (via ECK)
type: application
version: 0.1.0
appVersion: "8.5.1"

dependencies:
  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
