apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  routes:
    - kind: Rule
      match: Host(`grafana.wgbh-mla.org`)
      services:
        - kind: Service
          name: grafana
          port: 80
  tls:
    secretName: grafana-tls
