apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls-production
  namespace: whoami
spec:
  secretName: tls-whoami-production
  dnsNames:
    - w.wgbh-mla.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
