apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-tls-staging
  namespace: traefik
spec:
  secretName: tls-whoami-staging
  dnsNames:
    - whoami.wgbh-mla.org
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
