argo-cd:
  global:
    addPrometheusAnnotations: true
  dex:
    enabled: false  
  configs:
    cm:
      kustomize.buildOptions: --enable-helm
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hostname: cd.dev.wgbh-mla.org
      tls: true
