global:
  host: dev.wgbh-mla.org

hyrax:
  image:
    repository: ghcr.io/wgbh-mla/ams
    tag: d331bb3d
  fcrepo:
    enabled: false
  postgresql:
    enabled: false
  extraEnvVars:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ams-demo-db-cluster-app
          key: password
  externalPostgresql:
    username: app
    database: app
    host: ams-demo-db-cluster-rw
  worker:
    image:
      repository: ghcr.io/samvera/hyku/worker
      tag: 7b081416
      extraEnvVars:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ams-demo-db-cluster-app
              key: password

app-template:
  ingress:
    ams:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: "{{ .Release.Name }}.{{ .Values.global.host }}"
          paths:
            - path: /
              service:
                name: ams-demo-hyrax
                port: 80
      tls:
        - secretName: "{{ .Release.Name }}-tls"
          hosts:
            - "{{ .Release.Name }}.{{ .Values.global.host }}"
  rawResources:
    db-cluster:
      manifest:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        spec:
          spec:
            name: ams-db-cluster
            instances: 1
            imageName: ghcr.io/cloudnative-pg/postgresql:14.10
            storage:
              size: 10Gi
              storageClass: ebs-gp3-4
    database:
      manifest:
        apiVersion: postgresql.cnpg.io/v1
        kind: Database
        spec:
          spec:
            name: ams
            owner: app
            cluster:
              name: ams-db-cluster
