global:
  host: dev.wgbh-mla.org

hyrax:
  image:
    repository: ghcr.io/wgbh-mla/ams
    tag: 312b6eca
  fcrepo:
    enabled: false
  externalFcrepoHost: ams-db-cluster-rw
  postgresql:
    enabled: false
  externalPostgresql:
    host: ams-demo-db-cluster-rw
    username: app
    database: ams
    # password: 
  global:
    postgresql:
      auth:
        username: app
        # password: 
  worker:
    enabled: true
    image:
      repository: ghcr.io/samvera/hyku/worker
      tag: 7b081416
  # extraEnvFrom:
  #   - configMapRef:
  #       name: ams-demo-hyrax
  #   - secretRef:
  #       name: existingSecret
app-template:
  ingress:
    ams:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: "{{ .Release.Name }}.{{ .Values.global.host }}"
          paths:
            - path: /
              service:
                name: ams-demo-hyrax
                port: 80
      tls:
        - secretName: "{{ .Release.Name }}-tls"
          hosts:
            - "{{ .Release.Name }}.{{ .Values.global.host }}"
  rawResources:
    db-cluster:
      manifest:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        spec:
          name: ams-db-cluster
          instances: 1
          imageName: ghcr.io/cloudnative-pg/postgresql:18
          storage:
            size: 10Gi
            storageClass: ebs-gp3-4
    database:
      manifest:
        apiVersion: postgresql.cnpg.io/v1
        kind: Database
        spec:
          name: ams
          owner: app
          cluster:
            name: ams-db-cluster
