global:
  host: dev.wgbh-mla.org

hyrax:
  image:
    repository: ghcr.io/wgbh-mla/ams
    tag: 312b6eca
  fcrepo:
    enabled: false
  externalFcrepoHost: fcrepo
  postgresql:
    enabled: true
    image:
      repository: postgres
      tag: 18
  worker:
    enabled: true
    image:
      repository: ghcr.io/samvera/hyku/worker
      tag: 7b081416
  # extraEnvFrom:
  #   - configMapRef:
  #       name: ams-demo-hyrax
  #   - secretRef:
  #       name: existingSecret
app-template:
  ingress:
    ams:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: "{{ .Release.Name }}.{{ .Values.global.host }}"
          paths:
            - path: /
              service:
                name: ams-demo-hyrax
                port: 80
      tls:
        - secretName: "{{ .Release.Name }}-tls"
          hosts:
            - "{{ .Release.Name }}.{{ .Values.global.host }}"
