apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssl-certs
  namespace: traefik-demo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 128Mi
