apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch-stack
  namespace: argo-cd
spec:
  generators:
    - list:
        # List all applications to create
        elements:
          - name: elastic-operator
          - name: elasticsearch
          - name: kibana
          - name: elastic-connector
  template:
    metadata:
      name: '{{name}}'
      annotations:
        # Set sync-wave to control deployment order
        argocd.argoproj.io/sync-wave: |
          {{- if eq .name "operator" }}0{{- end }}
          {{- if eq .name "elasticsearch" }}1{{- end }}
          {{- if eq .name "kibana" }}2{{- end }}
          {{- if eq .name "connector" }}3{{- end }}
    spec:
      project: default
      source:
        repoURL: https://github.com/WGBH-MLA/cluster-deploy
        targetRevision: 24-elasticsearch-helm-charts   # branch to use for all apps
        path: elasticsearch/{{name}}                  # directory per chart
      destination:
        server: https://kubernetes.default.svc
        namespace: es
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
