grafana:
  persistence:
    enabled: true
prometheus:
  server:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    retention: 1y
    remoteWrite:
    - url: http://mimir-nginx.mimir/api/v1/push
  alertmanager:
    enabled: false
