grafana:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
    - grafana.dev.wgbh-mla.org
    tls:
    - secretName: grafana-tls-production
      hosts:
      - grafana.dev.wgbh-mla.org
  persistence:
    enabled: true

prometheus:
  server:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    retention: 1y
    remoteWrite:
    - url: http://mimir-nginx.mimir/api/v1/push
  alertmanager:
    enabled: false
