apiVersion: v2
name: traefik
version: 0.3.1
appVersion: v3.7.13
description: Traefik ingress controller and reverse proxy
dependencies:
- name: traefik
  repository: https://traefik.github.io/charts
  version: 41.6.1
