apiVersion: v2
name: traefik
version: 0.1.2
appVersion: v3.6.10
description: Traefik ingress controller and reverse proxy
dependencies:
- name: traefik
  repository: https://traefik.github.io/charts
  version: 39.0.5
