apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-http
spec:
  acme:
    email: ryan_harbert@wgbh.org
    privateKeySecretRef:
      name: letsencrypt-production-http
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik
          ingressTemplate:
            metadata:
              annotations:
                traefik.ingress.kubernetes.io/frontend-entry-points: web
