apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mla-eck-stack
  namespace: argo-cd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          # Use 'path' for local charts, use 'chart' for remote charts.
          # Use 'syncWave' to enforce order of deployments (operator needs to come first).
          - name: mla-eck-operator
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-eck-operator
            targetRevision: 0.1.0
            syncWave: 0
            namespace: elastic-system
          - name: mla-eck-elasticsearch
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-eck-elasticsearch
            targetRevision: 0.1.0
            syncWave: 1
            namespace: es
          - name: mla-eck-kibana
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-eck-kibana
            targetRevision: 0.1.3
            syncWave: 1
            namespace: es
          - name: mla-ingest-connector
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-ingest-connector
            targetRevision: 0.1.8
            syncWave: 1
            namespace: es
          - name: mla-external-secrets
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-external-secrets
            targetRevision: 0.1.2
            syncWave: 1
            namespace: external-secrets
  template:
    metadata:
      name: '{{.name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "{{.syncWave}}"
    spec:
      project: default
      source:
        repoURL: "{{.repoURL}}"
        chart: "{{.chart}}"
        path: "{{.path}}"
        targetRevision: "{{.targetRevision}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
