apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
spec:
  project: default
  sources:
    - chart: traefik
      repoURL: 'https://traefik.github.io/charts'
      targetRevision: 28.0.0
      helm:
        valueFiles:
          - $values/traefik/values.yml
    - ref: values
      targetRevision: HEAD
      repoURL: 'https://github.com/WGBH-MLA/cluster-deploy.git'
    - path: traefik/ssl-pv.yml
      targetRevision: HEAD
      repoURL: 'https://github.com/WGBH-MLA/cluster-deploy.git'

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
