USER-SUPPLIED VALUES:
additionalArguments:
- --log.filepath=/var/log/traefik/traefik.log
- --accesslog.filepath=/var/log/traefik/access.log
# - --entrypoints.web.http.middlewares=traefik-bouncer@kubernetescrd
# - --entrypoints.websecure.http.middlewares=traefik-bouncer@kubernetescrd
# - --entrypoints.websecure.http.middlewares=traefik-captcha-protect@kubernetescrd

certificatesResolvers:
  staging:
    acme:
      email: ryan_harbert@wgbh.org
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /ssl-certs/acme-staging.json
      tlsChallenge: true
  production:
    acme:
      email: ryan_harbert@wgbh.org
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /ssl-certs/acme-production.json
      tlsChallenge: true

env: null
ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: true

logs:
  access:
    enabled: true
    format: json
    # filePath: /var/log/access.log
    fields:
      headers:
        defaultmode: keep
  general:
    level: DEBUG

persistence:
  enabled: true
  existingClaim: ssl-certs
  path: /ssl-certs

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    forwardedHeaders:
      trustedIPs:
      - 10.0.32.0/24
    proxyProtocol:
      trustedIPs:
      - 10.0.0.0/16
    tls:
      certResolver: production
      enabled: true
    middlewares:
      - traefik-bouncer@kubernetescrd
      # - traefik-captcha-protect@kubernetescrd
  
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
  spec:
    externalTrafficPolicy: Local

securityContext:
  readOnlyRootFilesystem: False
  runAsGroup: 0
  runAsUser: 0
  runAsNonRoot: false

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.1
    captcha-protect:
      moduleName: github.com/libops/captcha-protect
      version: v1.0.0


providers:
  kubernetesIngress:
    allowExternalNameServices: true
  kubernetesCRD:
    enabled: true
    allowExternalNameServices: true