apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/WGBH-MLA/cluster-deploy.git
    path: influxdb
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: influxdb
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    createNamespace: true
