external-secrets:
  installCRDs: true
  replicaCount: 2
  serviceAccount:
    name: external-secrets-operator
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::127946490116:role/eso-irsa-role
