apiVersion: v2
name: argo-cd
version: 0.3.3
appVersion: v3.5.3
description: Application management and continuous deployment with Argo CD
dependencies:
- name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: 10.9.6
- name: argocd-image-updater
  repository: oci://ghcr.io/argoproj/argo-helm
  version: 1.3.0
