apiVersion: v2
name: rustfs
version: 0.0.5
appVersion: 1.0.0-rc.1
description: Helm chart for RustFS
dependencies:
- name: rustfs
  version: 1.0.0-rc.1
  repository: https://charts.rustfs.com
keywords:
- s3
- storage
maintainers:
- name: Harpo
  email: ryan_harbert@wgbh.org
sources:
- https://github.com/WGBH-MLA/cluster-deploy