apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connector.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "connector.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "connector.name" . }}
    spec:
      containers:
        - name: connector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
