apiVersion: v2
name: argo-cd
version: 0.1.0
appVersion: v3.1.0
description: Application management and continuous deployment with Argo CD
dependencies:
- name: argo-cd
  repository: https://argoproj.github.io/argo-helm
  version: 8.3.0
