apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mla-eck-stack
  namespace: argo-cd
spec:
  generators:
    - list:
        elements:
          # Use 'path' for local charts, use 'chart' for remote charts.
          # Use 'syncWave' to enforce order of deployments (operator needs to come first).
          - name: mla-eck-operator
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-eck-operator
            version: 0.1.0
            syncWave: 0
            valuesFiles:
              - mla-eck-operator/values.yaml
          - name: mla-eck-elasticsearch
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-eck-elasticsearch
            version: 0.1.0
            syncWave: 1
          - name: mla-eck-kibana
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            chart: mla-eck-kibana
            version: 0.1.0
            syncWave: 1
          - name: mla-ingest-connector
            repoURL: https://wgbh-mla.github.io/cluster-deploy
            path: mla-ingest-connector
            version: 0.1.0
            syncWave: 1
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: {{.syncWave}}
    spec:
      project: default
      source:
        repoURL: {{.repoURL}}
        {{- if .chart }}
        chart: {{.chart}}
        {{- else if .path }}
        path: {{.path}}
        {{- end }}
        targetRevision: {{.version}}
        {{- if .valuesFiles }}
        helm:
          valueFiles:
            {{- range .valuesFiles }}
              - {{ . }}
            {{- end }}
        {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: es
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
