tempo:
  tempo:
    metricsGenerator:
      enabled: true
      remoteWriteUrl: http://prometheus-server.prometheus:9090/api/v1/write

    #   processor:
    #     local_blocks:
    #       filter_server_spans: false
    # config:
    #   processor:
    #     local_blocks:
    #       flush_to_storage: true

    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo
          endpoint: minio.minio
          access_key: UmxOcXukanAZMSkUN5H9
          secret_key: vvQfETa6313tVrz7LYzUF8MwqeYJzTJjICQR7jNm
          insecure: true
    overrides:
      defaults:
        metrics_generator: 
          processors:
          - service-graphs
          - span-metrics
          - local-blocks
  metrics_generator:
    storage:
      path: /tmp/tempo/generator/wal
    traces_storage:
      path: /tmp/tempo/generator/traces