apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bouncer
  namespace: traefik
spec:
  plugin:
    bouncer:
      enabled: true
      # crowdsecMode: live
      # crowdsecMode: stream
      crowdsecMode: none
      # crowdsecMode: appsec
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.crowdsec:8080
      crowdsecLapiKey: yWGoPQeiq2/GgoLGNFCRtJrt6HYTYrPJD6/ofnu07kw
